server:
  port: 7772
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false
    username: order
    password: e6ZhRGBE6SKYhFXA
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: org.xr.order.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.xr: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
pattern:
  name: 本地环境local

#feign的日志
feign:
  client:
    config:
      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
        loggerLevel: full


